// Generated by CIRCT firtool-1.56.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module mem_48x32(	// src/main/scala/Lab3/memory.scala:16:26
  input  [5:0]  RW0_addr,
  input         RW0_en,
                RW0_clk,
                RW0_wmode,
  input  [31:0] RW0_wdata,
  output [31:0] RW0_rdata
);

  reg [31:0] Memory[0:47];	// src/main/scala/Lab3/memory.scala:16:26
  reg [5:0]  _RW0_raddr_d0;	// src/main/scala/Lab3/memory.scala:16:26
  reg        _RW0_ren_d0;	// src/main/scala/Lab3/memory.scala:16:26
  reg        _RW0_rmode_d0;	// src/main/scala/Lab3/memory.scala:16:26
  always @(posedge RW0_clk) begin	// src/main/scala/Lab3/memory.scala:16:26
    _RW0_raddr_d0 <= RW0_addr;	// src/main/scala/Lab3/memory.scala:16:26
    _RW0_ren_d0 <= RW0_en;	// src/main/scala/Lab3/memory.scala:16:26
    _RW0_rmode_d0 <= RW0_wmode;	// src/main/scala/Lab3/memory.scala:16:26
    if (RW0_en & RW0_wmode)	// src/main/scala/Lab3/memory.scala:16:26
      Memory[RW0_addr] <= RW0_wdata;	// src/main/scala/Lab3/memory.scala:16:26
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/Lab3/memory.scala:16:26
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/Lab3/memory.scala:16:26
      reg [31:0] _RANDOM;	// src/main/scala/Lab3/memory.scala:16:26
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/Lab3/memory.scala:16:26
    initial begin	// src/main/scala/Lab3/memory.scala:16:26
      `INIT_RANDOM_PROLOG_	// src/main/scala/Lab3/memory.scala:16:26
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/Lab3/memory.scala:16:26
        for (logic [5:0] i = 6'h0; i < 6'h30; i += 6'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/Lab3/memory.scala:16:26
          Memory[i] = _RANDOM_MEM;	// src/main/scala/Lab3/memory.scala:16:26
        end	// src/main/scala/Lab3/memory.scala:16:26
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/Lab3/memory.scala:16:26
        _RANDOM = {`RANDOM};	// src/main/scala/Lab3/memory.scala:16:26
        _RW0_raddr_d0 = _RANDOM[5:0];	// src/main/scala/Lab3/memory.scala:16:26
        _RW0_ren_d0 = _RANDOM[6];	// src/main/scala/Lab3/memory.scala:16:26
        _RW0_rmode_d0 = _RANDOM[7];	// src/main/scala/Lab3/memory.scala:16:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign RW0_rdata = _RW0_ren_d0 & ~_RW0_rmode_d0 ? Memory[_RW0_raddr_d0] : 32'bx;	// src/main/scala/Lab3/memory.scala:16:26
endmodule

module MatMem(	// <stdin>:3:3
  input         clock,	// <stdin>:4:11
  input  [5:0]  io_addr,	// src/main/scala/Lab3/memory.scala:8:16
  input         io_writeEn,	// src/main/scala/Lab3/memory.scala:8:16
                io_en,	// src/main/scala/Lab3/memory.scala:8:16
  input  [31:0] io_dataIn,	// src/main/scala/Lab3/memory.scala:8:16
  output [31:0] io_dataOut	// src/main/scala/Lab3/memory.scala:8:16
);

  wire        readEnable;	// src/main/scala/Lab3/memory.scala:16:26, :23:30, :24:31
  wire        writeEnable;	// src/main/scala/Lab3/memory.scala:20:21
  wire [31:0] _mem_ext_RW0_rdata;	// src/main/scala/Lab3/memory.scala:16:26
  assign writeEnable = io_writeEn & io_en;	// src/main/scala/Lab3/memory.scala:20:21
  wire        _GEN = io_en & ~io_writeEn;	// src/main/scala/Lab3/memory.scala:23:{15,17}
  assign readEnable = _GEN & io_en & ~io_writeEn;	// src/main/scala/Lab3/memory.scala:16:26, :23:{15,17,30}, :24:31
  mem_48x32 mem_ext (	// src/main/scala/Lab3/memory.scala:16:26
    .RW0_addr  (io_addr),
    .RW0_en    (readEnable | writeEnable),	// src/main/scala/Lab3/memory.scala:16:26, :20:21, :23:30, :24:31
    .RW0_clk   (clock),
    .RW0_wmode (io_writeEn),
    .RW0_wdata (io_dataIn),
    .RW0_rdata (_mem_ext_RW0_rdata)
  );
  assign io_dataOut = _GEN ? _mem_ext_RW0_rdata : 32'h0;	// <stdin>:3:3, src/main/scala/Lab3/memory.scala:16:26, :19:16, :23:{15,30}, :24:20
endmodule

module AdderTree(	// <stdin>:27:3
  input  [31:0] io_inputs_0,	// src/main/scala/Lab3/AdderTree.scala:9:14
                io_inputs_1,	// src/main/scala/Lab3/AdderTree.scala:9:14
                io_inputs_2,	// src/main/scala/Lab3/AdderTree.scala:9:14
                io_inputs_3,	// src/main/scala/Lab3/AdderTree.scala:9:14
  output [33:0] io_output	// src/main/scala/Lab3/AdderTree.scala:9:14
);

  wire [32:0] _io_output_T =
    {io_inputs_0[31], io_inputs_0} + {io_inputs_1[31], io_inputs_1};	// src/main/scala/Lab3/AdderTree.scala:15:37
  assign io_output =
    {_io_output_T[32], _io_output_T} + {{2{io_inputs_2[31]}}, io_inputs_2}
    + {{2{io_inputs_3[31]}}, io_inputs_3};	// <stdin>:27:3, src/main/scala/Lab3/AdderTree.scala:15:37
endmodule

module MatMulModule(	// <stdin>:37:3
  input         clock,	// <stdin>:38:11
                reset,	// <stdin>:39:11
  input  [31:0] io_dataIn,	// src/main/scala/Lab3/MatMulModule.scala:11:17
  input         io_start,	// src/main/scala/Lab3/MatMulModule.scala:11:17
  output [5:0]  io_addr,	// src/main/scala/Lab3/MatMulModule.scala:11:17
  output        io_writeEn,	// src/main/scala/Lab3/MatMulModule.scala:11:17
                io_enable,	// src/main/scala/Lab3/MatMulModule.scala:11:17
  output [31:0] io_dataOut,	// src/main/scala/Lab3/MatMulModule.scala:11:17
  output        io_busy	// src/main/scala/Lab3/MatMulModule.scala:11:17
);

  wire [33:0] _adderTree_io_output;	// src/main/scala/Lab3/MatMulModule.scala:137:33
  reg  [7:0]  index;	// src/main/scala/Lab3/MatMulModule.scala:28:23
  reg  [1:0]  buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25
  wire        _io_addr_T = buf_sel == 2'h0;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :33:48
  reg  [7:0]  matA_buf_0;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_1;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_2;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_3;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_4;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_5;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_6;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_7;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_8;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_9;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_10;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_11;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_12;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_13;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_14;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matA_buf_15;	// src/main/scala/Lab3/MatMulModule.scala:45:47
  reg  [7:0]  matB_buf_0;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_1;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_2;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_3;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_4;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_5;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_6;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_7;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_8;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_9;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_10;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_11;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_12;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_13;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_14;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [7:0]  matB_buf_15;	// src/main/scala/Lab3/MatMulModule.scala:48:47
  reg  [1:0]  state;	// src/main/scala/Lab3/MatMulModule.scala:60:21
  wire        _en_load_T_95 = buf_sel == 2'h1;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :64:17, :74:22
  wire        _GEN = state == 2'h0;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :60:21, :69:5
  wire        _GEN_0 = state == 2'h1;	// src/main/scala/Lab3/MatMulModule.scala:60:21, :69:5, :74:22
  reg         en_load_REG;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_1;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_2;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_3;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_4;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_5;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_6;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_7;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_8;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_9;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_10;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_11;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_12;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_13;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_14;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_15;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_16;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_17;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_18;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_19;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_20;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_21;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_22;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_23;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_24;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_25;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_26;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_27;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_28;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_29;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_30;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_31;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_32;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_33;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_34;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_35;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_36;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_37;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_38;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_39;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_40;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_41;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_42;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_43;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_44;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_45;	// src/main/scala/Lab3/MatMulModule.scala:86:36
  reg  [7:0]  en_load_REG_46;	// src/main/scala/Lab3/MatMulModule.scala:86:61
  reg  [1:0]  en_load_REG_47;	// src/main/scala/Lab3/MatMulModule.scala:86:77
  reg         en_load_REG_48;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_49;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_50;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_51;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_52;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_53;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_54;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_55;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_56;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_57;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_58;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_59;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_60;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_61;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_62;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_63;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_64;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_65;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_66;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_67;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_68;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_69;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_70;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_71;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_72;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_73;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_74;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_75;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_76;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_77;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  reg         en_load_REG_78;	// src/main/scala/Lab3/MatMulModule.scala:93:36
  reg  [7:0]  en_load_REG_79;	// src/main/scala/Lab3/MatMulModule.scala:93:61
  wire        _GEN_1 = state == 2'h2;	// src/main/scala/Lab3/MatMulModule.scala:60:21, :65:17, :69:5
  wire        _GEN_2 = _GEN | _GEN_0;	// src/main/scala/Lab3/MatMulModule.scala:42:14, :69:5, :81:23
  wire        _io_enable_output = ~_GEN & (_GEN_0 | _GEN_1);	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :82:22
  wire [7:0]  _GEN_3 = index / 8'h4;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:51, :112:39
  wire        _GEN_4 = _GEN_3 == 8'h0;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :112:{28,39}
  wire        _GEN_5 = _GEN_3 == 8'h1;	// src/main/scala/Lab3/MatMulModule.scala:36:14, :112:{28,39}
  wire        _GEN_6 = _GEN_3 == 8'h2;	// src/main/scala/Lab3/MatMulModule.scala:86:51, :112:{28,39}
  wire        _GEN_7 = _GEN_3 == 8'h3;	// src/main/scala/Lab3/MatMulModule.scala:86:51, :112:{28,39}
  wire        _GEN_8 = _GEN_2 | ~_GEN_1;	// src/main/scala/Lab3/MatMulModule.scala:42:14, :53:29, :69:5, :81:23
  wire [7:0]  _GEN_9 = index % 8'h4;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:51, :123:39
  wire        _GEN_10 = _GEN_9[2:0] == 3'h0;	// src/main/scala/Lab3/MatMulModule.scala:33:16, :123:{28,39}
  wire        _GEN_11 = _GEN_9[2:0] == 3'h1;	// src/main/scala/Lab3/MatMulModule.scala:123:{28,39}
  wire        _GEN_12 = _GEN_9[2:0] == 3'h2;	// src/main/scala/Lab3/MatMulModule.scala:123:{28,39}
  wire        _GEN_13 = _GEN_9[2:0] == 3'h3;	// src/main/scala/Lab3/MatMulModule.scala:123:{28,39}
  always @(posedge clock) begin	// <stdin>:38:11
    if (reset) begin	// <stdin>:38:11
      index <= 8'h0;	// src/main/scala/Lab3/MatMulModule.scala:28:23
      buf_sel <= 2'h0;	// src/main/scala/Lab3/MatMulModule.scala:31:25
      state <= 2'h0;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :60:21
    end
    else begin	// <stdin>:38:11
      automatic logic            _GEN_14;	// src/main/scala/Lab3/MatMulModule.scala:33:16
      automatic logic            _GEN_15;	// src/main/scala/Lab3/MatMulModule.scala:33:38
      automatic logic [1:0]      _GEN_16;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :34:5, :35:16
      automatic logic            _GEN_17;	// src/main/scala/Lab3/MatMulModule.scala:99:24
      automatic logic [3:0][7:0] _GEN_18;	// src/main/scala/Lab3/MatMulModule.scala:34:5, :69:5, :73:13, :100:13, :142:13, :163:18
      automatic logic [3:0][1:0] _GEN_19;	// src/main/scala/Lab3/MatMulModule.scala:34:5, :69:5, :73:13, :100:13
      automatic logic [3:0][1:0] _GEN_20;	// src/main/scala/Lab3/MatMulModule.scala:60:21, :69:5, :73:13, :100:13, :142:13, :161:18
      _GEN_14 = index == 8'h10;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :33:16
      _GEN_15 = _GEN_14 & _io_addr_T;	// src/main/scala/Lab3/MatMulModule.scala:33:{16,38,48}
      _GEN_16 = _GEN_15 ? 2'h1 : buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :33:38, :34:5, :35:16, :74:22
      _GEN_17 = index == 8'h20;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :99:24
      _GEN_18 =
        {{8'h0},
         {_GEN_14 ? 8'h0 : index + 8'h1},
         {_GEN_17 ? 8'h0 : index + 8'h1},
         {io_start ? 8'h0 : _GEN_15 ? 8'h1 : index}};	// src/main/scala/Lab3/MatMulModule.scala:28:23, :33:{16,38}, :34:5, :36:14, :69:5, :73:13, :75:22, :88:28, :95:21, :99:24, :100:13, :102:22, :140:{18,25}, :142:13, :143:22, :163:18
      index <= _GEN_18[state];	// src/main/scala/Lab3/MatMulModule.scala:28:23, :34:5, :60:21, :69:5, :73:13, :100:13, :142:13, :163:18
      _GEN_19 =
        {{_GEN_1 | ~(&state) ? _GEN_16 : 2'h0},
         {_GEN_16},
         {_GEN_17 ? 2'h2 : _GEN_16},
         {io_start ? 2'h0 : _GEN_16}};	// src/main/scala/Lab3/MatMulModule.scala:31:25, :34:5, :35:16, :60:21, :65:17, :69:5, :73:13, :76:24, :99:24, :100:13, :103:24
      buf_sel <= _GEN_19[state];	// src/main/scala/Lab3/MatMulModule.scala:31:25, :34:5, :60:21, :69:5, :73:13, :100:13
      _GEN_20 =
        {{2'h0},
         {_GEN_14 ? 2'h3 : state},
         {_GEN_17 ? 2'h2 : state},
         {io_start ? 2'h1 : state}};	// src/main/scala/Lab3/MatMulModule.scala:31:25, :33:16, :60:21, :65:17, :69:5, :73:13, :74:22, :86:51, :99:24, :100:13, :101:22, :142:13, :144:22, :161:18
      state <= _GEN_20[state];	// src/main/scala/Lab3/MatMulModule.scala:60:21, :69:5, :73:13, :100:13, :142:13, :161:18
    end
    if (_GEN
        | ~(_GEN_0 & en_load_REG & en_load_REG_1 == 8'h0 & en_load_REG_2 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:28:23, :31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_0 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_3 & en_load_REG_4 == 8'h1 & en_load_REG_5 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :36:14, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_1 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_6 & en_load_REG_7 == 8'h2 & en_load_REG_8 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_2 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_9 & en_load_REG_10 == 8'h3
            & en_load_REG_11 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_3 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_12 & en_load_REG_13 == 8'h4
            & en_load_REG_14 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_4 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_15 & en_load_REG_16 == 8'h5
            & en_load_REG_17 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_5 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_18 & en_load_REG_19 == 8'h6
            & en_load_REG_20 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_6 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_21 & en_load_REG_22 == 8'h7
            & en_load_REG_23 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_7 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_24 & en_load_REG_25 == 8'h8
            & en_load_REG_26 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_8 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_27 & en_load_REG_28 == 8'h9
            & en_load_REG_29 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_9 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_30 & en_load_REG_31 == 8'hA
            & en_load_REG_32 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_10 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_33 & en_load_REG_34 == 8'hB
            & en_load_REG_35 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_11 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_36 & en_load_REG_37 == 8'hC
            & en_load_REG_38 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_12 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_39 & en_load_REG_40 == 8'hD
            & en_load_REG_41 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_13 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_42 & en_load_REG_43 == 8'hE
            & en_load_REG_44 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_14 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN
        | ~(_GEN_0 & en_load_REG_45 & en_load_REG_46 == 8'hF
            & en_load_REG_47 == 2'h0)) begin	// src/main/scala/Lab3/MatMulModule.scala:31:25, :45:47, :69:5, :86:{36,51,61,77,86}, :87:27
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:45:47, :69:5
      matA_buf_15 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :45:47
    if (_GEN | ~(_GEN_0 & en_load_REG_48 & en_load_REG_49 == 8'h10 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:33:16, :48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_0 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_50 & en_load_REG_51 == 8'h11 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_1 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_52 & en_load_REG_53 == 8'h12 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_2 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_54 & en_load_REG_55 == 8'h13 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_3 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_56 & en_load_REG_57 == 8'h14 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_4 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_58 & en_load_REG_59 == 8'h15 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_5 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_60 & en_load_REG_61 == 8'h16 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_6 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_62 & en_load_REG_63 == 8'h17 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_7 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_64 & en_load_REG_65 == 8'h18 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_8 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_66 & en_load_REG_67 == 8'h19 & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_9 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_68 & en_load_REG_69 == 8'h1A & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_10 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_70 & en_load_REG_71 == 8'h1B & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_11 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_72 & en_load_REG_73 == 8'h1C & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_12 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_74 & en_load_REG_75 == 8'h1D & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_13 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_76 & en_load_REG_77 == 8'h1E & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_14 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    if (_GEN | ~(_GEN_0 & en_load_REG_78 & en_load_REG_79 == 8'h1F & _en_load_T_95)) begin	// src/main/scala/Lab3/MatMulModule.scala:48:47, :64:17, :69:5, :93:{36,51,61}, :94:44
    end
    else	// src/main/scala/Lab3/MatMulModule.scala:48:47, :69:5
      matB_buf_15 <= io_dataIn[7:0];	// src/main/scala/Lab3/MatMulModule.scala:11:17, :48:47
    en_load_REG <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_1 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_2 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_3 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_4 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_5 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_6 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_7 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_8 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_9 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_10 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_11 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_12 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_13 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_14 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_15 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_16 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_17 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_18 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_19 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_20 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_21 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_22 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_23 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_24 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_25 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_26 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_27 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_28 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_29 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_30 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_31 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_32 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_33 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_34 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_35 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_36 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_37 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_38 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_39 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_40 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_41 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_42 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_43 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_44 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_45 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :86:36
    en_load_REG_46 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :86:61
    en_load_REG_47 <= buf_sel;	// src/main/scala/Lab3/MatMulModule.scala:31:25, :86:77
    en_load_REG_48 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_49 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_50 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_51 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_52 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_53 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_54 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_55 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_56 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_57 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_58 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_59 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_60 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_61 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_62 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_63 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_64 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_65 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_66 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_67 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_68 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_69 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_70 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_71 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_72 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_73 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_74 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_75 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_76 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_77 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
    en_load_REG_78 <= _io_enable_output;	// src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5, :93:36
    en_load_REG_79 <= index;	// src/main/scala/Lab3/MatMulModule.scala:28:23, :93:61
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:37:3
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:37:3
      `FIRRTL_BEFORE_INITIAL	// <stdin>:37:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:37:3
      automatic logic [31:0] _RANDOM[0:18];	// <stdin>:37:3
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:37:3
        `INIT_RANDOM_PROLOG_	// <stdin>:37:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:37:3
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// <stdin>:37:3
        end	// <stdin>:37:3
        index = _RANDOM[5'h0][7:0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:28:23
        buf_sel = _RANDOM[5'h0][17:16];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:28:23, :31:25
        matA_buf_0 = _RANDOM[5'h0][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:28:23, :45:47
        matA_buf_1 = {_RANDOM[5'h0][31:26], _RANDOM[5'h1][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:28:23, :45:47
        matA_buf_2 = _RANDOM[5'h1][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_3 = _RANDOM[5'h1][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_4 = _RANDOM[5'h1][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_5 = {_RANDOM[5'h1][31:26], _RANDOM[5'h2][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_6 = _RANDOM[5'h2][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_7 = _RANDOM[5'h2][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_8 = _RANDOM[5'h2][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_9 = {_RANDOM[5'h2][31:26], _RANDOM[5'h3][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_10 = _RANDOM[5'h3][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_11 = _RANDOM[5'h3][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_12 = _RANDOM[5'h3][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_13 = {_RANDOM[5'h3][31:26], _RANDOM[5'h4][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_14 = _RANDOM[5'h4][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matA_buf_15 = _RANDOM[5'h4][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47
        matB_buf_0 = _RANDOM[5'h4][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47, :48:47
        matB_buf_1 = {_RANDOM[5'h4][31:26], _RANDOM[5'h5][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:45:47, :48:47
        matB_buf_2 = _RANDOM[5'h5][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_3 = _RANDOM[5'h5][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_4 = _RANDOM[5'h5][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_5 = {_RANDOM[5'h5][31:26], _RANDOM[5'h6][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_6 = _RANDOM[5'h6][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_7 = _RANDOM[5'h6][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_8 = _RANDOM[5'h6][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_9 = {_RANDOM[5'h6][31:26], _RANDOM[5'h7][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_10 = _RANDOM[5'h7][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_11 = _RANDOM[5'h7][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_12 = _RANDOM[5'h7][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_13 = {_RANDOM[5'h7][31:26], _RANDOM[5'h8][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_14 = _RANDOM[5'h8][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        matB_buf_15 = _RANDOM[5'h8][17:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47
        state = _RANDOM[5'h8][19:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47, :60:21
        en_load_REG = _RANDOM[5'h8][20];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47, :86:36
        en_load_REG_1 = _RANDOM[5'h8][28:21];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47, :86:61
        en_load_REG_2 = _RANDOM[5'h8][30:29];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47, :86:77
        en_load_REG_3 = _RANDOM[5'h8][31];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:48:47, :86:36
        en_load_REG_4 = _RANDOM[5'h9][7:0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61
        en_load_REG_5 = _RANDOM[5'h9][9:8];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_6 = _RANDOM[5'h9][10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_7 = _RANDOM[5'h9][18:11];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61
        en_load_REG_8 = _RANDOM[5'h9][20:19];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_9 = _RANDOM[5'h9][21];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_10 = _RANDOM[5'h9][29:22];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61
        en_load_REG_11 = _RANDOM[5'h9][31:30];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_12 = _RANDOM[5'hA][0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:36
        en_load_REG_13 = _RANDOM[5'hA][8:1];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_14 = _RANDOM[5'hA][10:9];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_15 = _RANDOM[5'hA][11];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:36
        en_load_REG_16 = _RANDOM[5'hA][19:12];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_17 = _RANDOM[5'hA][21:20];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_18 = _RANDOM[5'hA][22];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:36
        en_load_REG_19 = _RANDOM[5'hA][30:23];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_20 = {_RANDOM[5'hA][31], _RANDOM[5'hB][0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_21 = _RANDOM[5'hB][1];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_22 = _RANDOM[5'hB][9:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_23 = _RANDOM[5'hB][11:10];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:77
        en_load_REG_24 = _RANDOM[5'hB][12];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_25 = _RANDOM[5'hB][20:13];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_26 = _RANDOM[5'hB][22:21];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:77
        en_load_REG_27 = _RANDOM[5'hB][23];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_28 = _RANDOM[5'hB][31:24];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_29 = _RANDOM[5'hC][1:0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:77
        en_load_REG_30 = _RANDOM[5'hC][2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_31 = _RANDOM[5'hC][10:3];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_32 = _RANDOM[5'hC][12:11];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:77
        en_load_REG_33 = _RANDOM[5'hC][13];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_34 = _RANDOM[5'hC][21:14];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_35 = _RANDOM[5'hC][23:22];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:77
        en_load_REG_36 = _RANDOM[5'hC][24];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,77}
        en_load_REG_37 = {_RANDOM[5'hC][31:25], _RANDOM[5'hD][0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_38 = _RANDOM[5'hD][2:1];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_39 = _RANDOM[5'hD][3];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_40 = _RANDOM[5'hD][11:4];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61
        en_load_REG_41 = _RANDOM[5'hD][13:12];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_42 = _RANDOM[5'hD][14];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_43 = _RANDOM[5'hD][22:15];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61
        en_load_REG_44 = _RANDOM[5'hD][24:23];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_45 = _RANDOM[5'hD][25];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{36,61}
        en_load_REG_46 = {_RANDOM[5'hD][31:26], _RANDOM[5'hE][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61
        en_load_REG_47 = _RANDOM[5'hE][3:2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:{61,77}
        en_load_REG_48 = _RANDOM[5'hE][4];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:36
        en_load_REG_49 = _RANDOM[5'hE][12:5];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:61
        en_load_REG_50 = _RANDOM[5'hE][13];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:36
        en_load_REG_51 = _RANDOM[5'hE][21:14];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:61
        en_load_REG_52 = _RANDOM[5'hE][22];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:36
        en_load_REG_53 = _RANDOM[5'hE][30:23];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:61
        en_load_REG_54 = _RANDOM[5'hE][31];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:86:61, :93:36
        en_load_REG_55 = _RANDOM[5'hF][7:0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_56 = _RANDOM[5'hF][8];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_57 = _RANDOM[5'hF][16:9];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_58 = _RANDOM[5'hF][17];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_59 = _RANDOM[5'hF][25:18];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_60 = _RANDOM[5'hF][26];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_61 = {_RANDOM[5'hF][31:27], _RANDOM[5'h10][2:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_62 = _RANDOM[5'h10][3];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_63 = _RANDOM[5'h10][11:4];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_64 = _RANDOM[5'h10][12];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_65 = _RANDOM[5'h10][20:13];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_66 = _RANDOM[5'h10][21];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_67 = _RANDOM[5'h10][29:22];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_68 = _RANDOM[5'h10][30];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_69 = {_RANDOM[5'h10][31], _RANDOM[5'h11][6:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_70 = _RANDOM[5'h11][7];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_71 = _RANDOM[5'h11][15:8];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_72 = _RANDOM[5'h11][16];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_73 = _RANDOM[5'h11][24:17];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_74 = _RANDOM[5'h11][25];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_75 = {_RANDOM[5'h11][31:26], _RANDOM[5'h12][1:0]};	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_76 = _RANDOM[5'h12][2];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_77 = _RANDOM[5'h12][10:3];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
        en_load_REG_78 = _RANDOM[5'h12][11];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:{36,61}
        en_load_REG_79 = _RANDOM[5'h12][19:12];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:93:61
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:37:3
      `FIRRTL_AFTER_INITIAL	// <stdin>:37:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AdderTree adderTree (	// src/main/scala/Lab3/MatMulModule.scala:137:33
    .io_inputs_0
      ((_GEN_8
          ? 32'h0
          : _GEN_13
              ? {{24{matB_buf_3[7]}}, matB_buf_3}
              : _GEN_12
                  ? {{24{matB_buf_2[7]}}, matB_buf_2}
                  : _GEN_11
                      ? {{24{matB_buf_1[7]}}, matB_buf_1}
                      : _GEN_10 ? {{24{matB_buf_0[7]}}, matB_buf_0} : 32'h0)
       * (_GEN_8
            ? 32'h0
            : _GEN_7
                ? {24'h0, matA_buf_12}
                : _GEN_6
                    ? {24'h0, matA_buf_8}
                    : _GEN_5
                        ? {24'h0, matA_buf_4}
                        : _GEN_4 ? {24'h0, matA_buf_0} : 32'h0)),	// src/main/scala/Lab3/MatMulModule.scala:40:14, :45:47, :48:47, :53:29, :54:29, :69:5, :87:32, :94:49, :112:28, :113:17, :116:43, :123:28, :124:17, :127:43, :134:42
    .io_inputs_1
      ((_GEN_8
          ? 32'h0
          : _GEN_13
              ? {{24{matB_buf_7[7]}}, matB_buf_7}
              : _GEN_12
                  ? {{24{matB_buf_6[7]}}, matB_buf_6}
                  : _GEN_11
                      ? {{24{matB_buf_5[7]}}, matB_buf_5}
                      : _GEN_10 ? {{24{matB_buf_4[7]}}, matB_buf_4} : 32'h0)
       * (_GEN_8
            ? 32'h0
            : _GEN_7
                ? {24'h0, matA_buf_13}
                : _GEN_6
                    ? {24'h0, matA_buf_9}
                    : _GEN_5
                        ? {24'h0, matA_buf_5}
                        : _GEN_4 ? {24'h0, matA_buf_1} : 32'h0)),	// src/main/scala/Lab3/MatMulModule.scala:40:14, :45:47, :48:47, :53:29, :54:29, :69:5, :87:32, :94:49, :112:28, :113:17, :116:43, :123:28, :124:17, :127:43, :134:42
    .io_inputs_2
      ((_GEN_8
          ? 32'h0
          : _GEN_13
              ? {{24{matB_buf_11[7]}}, matB_buf_11}
              : _GEN_12
                  ? {{24{matB_buf_10[7]}}, matB_buf_10}
                  : _GEN_11
                      ? {{24{matB_buf_9[7]}}, matB_buf_9}
                      : _GEN_10 ? {{24{matB_buf_8[7]}}, matB_buf_8} : 32'h0)
       * (_GEN_8
            ? 32'h0
            : _GEN_7
                ? {24'h0, matA_buf_14}
                : _GEN_6
                    ? {24'h0, matA_buf_10}
                    : _GEN_5
                        ? {24'h0, matA_buf_6}
                        : _GEN_4 ? {24'h0, matA_buf_2} : 32'h0)),	// src/main/scala/Lab3/MatMulModule.scala:40:14, :45:47, :48:47, :53:29, :54:29, :69:5, :87:32, :94:49, :112:28, :113:17, :116:43, :123:28, :124:17, :127:43, :134:42
    .io_inputs_3
      ((_GEN_8
          ? 32'h0
          : _GEN_13
              ? {{24{matB_buf_15[7]}}, matB_buf_15}
              : _GEN_12
                  ? {{24{matB_buf_14[7]}}, matB_buf_14}
                  : _GEN_11
                      ? {{24{matB_buf_13[7]}}, matB_buf_13}
                      : _GEN_10 ? {{24{matB_buf_12[7]}}, matB_buf_12} : 32'h0)
       * (_GEN_8
            ? 32'h0
            : _GEN_7
                ? {24'h0, matA_buf_15}
                : _GEN_6
                    ? {24'h0, matA_buf_11}
                    : _GEN_5
                        ? {24'h0, matA_buf_7}
                        : _GEN_4 ? {24'h0, matA_buf_3} : 32'h0)),	// src/main/scala/Lab3/MatMulModule.scala:40:14, :45:47, :48:47, :53:29, :54:29, :69:5, :87:32, :94:49, :112:28, :113:17, :116:43, :123:28, :124:17, :127:43, :134:42
    .io_output   (_adderTree_io_output)
  );
  assign io_addr =
    (_io_addr_T | _en_load_T_95 ? 6'h0 : {buf_sel == 2'h2, 5'h0}) + index[5:0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:28:23, :31:25, :33:48, :64:17, :65:17, :66:4, src/main/scala/chisel3/util/Mux.scala:141:16
  assign io_writeEn = ~_GEN_2 & _GEN_1;	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:42:14, :69:5, :81:23
  assign io_enable = _io_enable_output;	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:43:13, :69:5
  assign io_dataOut = _GEN_8 ? 32'h0 : _adderTree_io_output[31:0];	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:40:14, :53:29, :69:5, :137:33, :139:23
  assign io_busy = _GEN | _GEN_0 | _GEN_1 | ~(&state);	// <stdin>:37:3, src/main/scala/Lab3/MatMulModule.scala:33:48, :35:16, :41:11, :60:21, :69:5, :160:20
endmodule

module MM_TOP(	// <stdin>:825:3
  input         clock,	// <stdin>:826:11
                reset,	// <stdin>:827:11
  input  [31:0] io_dataIn,	// src/main/scala/Lab3/Top.scala:27:16
  input  [5:0]  io_addr,	// src/main/scala/Lab3/Top.scala:27:16
  input         io_writeEn,	// src/main/scala/Lab3/Top.scala:27:16
                io_enable,	// src/main/scala/Lab3/Top.scala:27:16
  input  [1:0]  io_op,	// src/main/scala/Lab3/Top.scala:27:16
  input         io_start,	// src/main/scala/Lab3/Top.scala:27:16
  output [31:0] io_dataOut,	// src/main/scala/Lab3/Top.scala:27:16
  output        io_busy	// src/main/scala/Lab3/Top.scala:27:16
);

  wire [5:0]  _mat_module_io_addr;	// src/main/scala/Lab3/Top.scala:50:26
  wire        _mat_module_io_writeEn;	// src/main/scala/Lab3/Top.scala:50:26
  wire        _mat_module_io_enable;	// src/main/scala/Lab3/Top.scala:50:26
  wire [31:0] _mat_module_io_dataOut;	// src/main/scala/Lab3/Top.scala:50:26
  wire [31:0] _memory_module_io_dataOut;	// src/main/scala/Lab3/Top.scala:48:29
  MatMem memory_module (	// src/main/scala/Lab3/Top.scala:48:29
    .clock      (clock),
    .io_addr    ((|io_op) ? io_addr : _mat_module_io_addr),	// src/main/scala/Lab3/Top.scala:50:26, :53:35, :54:31
    .io_writeEn ((|io_op) ? io_writeEn : _mat_module_io_writeEn),	// src/main/scala/Lab3/Top.scala:50:26, :53:35, :55:34
    .io_en      ((|io_op) ? io_enable : _mat_module_io_enable),	// src/main/scala/Lab3/Top.scala:50:26, :53:35, :56:29
    .io_dataIn  ((|io_op) ? io_dataIn : _mat_module_io_dataOut),	// src/main/scala/Lab3/Top.scala:50:26, :53:35, :57:33
    .io_dataOut (_memory_module_io_dataOut)
  );
  MatMulModule mat_module (	// src/main/scala/Lab3/Top.scala:50:26
    .clock      (clock),
    .reset      (reset),
    .io_dataIn  (_memory_module_io_dataOut),	// src/main/scala/Lab3/Top.scala:48:29
    .io_start   (io_start),
    .io_addr    (_mat_module_io_addr),
    .io_writeEn (_mat_module_io_writeEn),
    .io_enable  (_mat_module_io_enable),
    .io_dataOut (_mat_module_io_dataOut),
    .io_busy    (io_busy)
  );
  assign io_dataOut = _memory_module_io_dataOut;	// <stdin>:825:3, src/main/scala/Lab3/Top.scala:48:29
endmodule

module FPGAshell(	// <stdin>:851:3
  input  clock,	// <stdin>:852:11
         reset,	// <stdin>:853:11
         io_start,	// src/main/scala/fpga_lab3/fpga_shell.scala:39:16
         io_check,	// src/main/scala/fpga_lab3/fpga_shell.scala:39:16
  output io_finish,	// src/main/scala/fpga_lab3/fpga_shell.scala:39:16
         io_correct	// src/main/scala/fpga_lab3/fpga_shell.scala:39:16
);

  wire [31:0]       _dut_io_dataOut;	// src/main/scala/fpga_lab3/fpga_shell.scala:57:19
  wire              _dut_io_busy;	// src/main/scala/fpga_lab3/fpga_shell.scala:57:19
  wire [63:0][31:0] _GEN =
    {32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hF5,
     32'hFFFFBA95,
     32'hFFFFD3B8,
     32'hFFFFEDD2,
     32'hFFFFD200,
     32'hFFFF84E9,
     32'hFFFFAAB6,
     32'hFFFFCF22,
     32'hFFFFAFB6,
     32'hFFFF609D,
     32'hFFFF98A8,
     32'hFFFFB287,
     32'hFFFF83AA,
     32'hFFFF452D,
     32'hFFFF7A98,
     32'hFFFF9F38,
     32'hFFFF7F14,
     32'hFFFFFFAB,
     32'hFFFFFFCC,
     32'hFFFFFF89,
     32'hFFFFFF8A,
     32'hFFFFFFB2,
     32'hFFFFFFD2,
     32'hFFFFFFEF,
     32'hFFFFFFC8,
     32'hFFFFFF9F,
     32'hFFFFFFAA,
     32'hFFFFFFE4,
     32'hFFFFFFE6,
     32'hFFFFFFE2,
     32'hFFFFFFF0,
     32'hFFFFFFFD,
     32'hFFFFFFEA,
     32'hA,
     32'h77,
     32'h25,
     32'h87,
     32'h38,
     32'h64,
     32'h7B,
     32'hEA,
     32'h6D,
     32'hE8,
     32'h56,
     32'hAA,
     32'h89,
     32'h6A,
     32'hD4,
     32'hF5};	// src/main/scala/fpga_lab3/fpga_shell.scala:103:26
  reg               result_correct;	// src/main/scala/fpga_lab3/fpga_shell.scala:60:31
  reg               finish_exe;	// src/main/scala/fpga_lab3/fpga_shell.scala:61:27
  reg  [5:0]        mem_addr;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25
  reg  [5:0]        rom_addr;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25
  reg  [2:0]        state;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24
  wire              _GEN_0 = state == 3'h0;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :84:5
  wire              _GEN_1 = state == 3'h1;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :79:25, :84:5
  wire              _GEN_2 = state == 3'h2;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :79:43, :84:5
  wire              _GEN_3 = state == 3'h3;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :84:5, :121:20
  wire              _GEN_4 = _GEN_1 | _GEN_2;	// src/main/scala/fpga_lab3/fpga_shell.scala:70:18, :84:5
  wire              _GEN_5 = state == 3'h5;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :79:59, :84:5
  wire              is_last = mem_addr == 6'h30;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :135:34
  wire              _GEN_6 = _GEN_3 | state == 3'h4;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :77:24, :84:5, :126:18
  wire              _GEN_7 = ~_GEN_0 & (_GEN_4 | ~_GEN_6 & _GEN_5 & ~is_last);	// src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :62:25, :68:19, :69:18, :70:18, :79:19, :84:5, :105:26, :116:26, :135:34, :137:31
  reg               REG;	// src/main/scala/fpga_lab3/fpga_shell.scala:140:25
  always @(posedge clock) begin	// <stdin>:852:11
    if (reset) begin	// <stdin>:852:11
      result_correct <= 1'h0;	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31
      finish_exe <= 1'h0;	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:61:27
      mem_addr <= 6'h0;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25
      rom_addr <= 6'h0;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :63:25
      state <= 3'h0;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24
    end
    else begin	// <stdin>:852:11
      automatic logic [63:0][31:0] _GEN_8 =
        {32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hF5,
         32'hFFFFBA95,
         32'hFFFFD3B8,
         32'hFFFFEDD2,
         32'hFFFFD200,
         32'hFFFF84E9,
         32'hFFFFAAB6,
         32'hFFFFCF22,
         32'hFFFFAFB6,
         32'hFFFF609D,
         32'hFFFF98A8,
         32'hFFFFB287,
         32'hFFFF83AA,
         32'hFFFF452D,
         32'hFFFF7A98,
         32'hFFFF9F38,
         32'hFFFF7F14,
         32'hFFFFFFAB,
         32'hFFFFFFCC,
         32'hFFFFFF89,
         32'hFFFFFF8A,
         32'hFFFFFFB2,
         32'hFFFFFFD2,
         32'hFFFFFFEF,
         32'hFFFFFFC8,
         32'hFFFFFF9F,
         32'hFFFFFFAA,
         32'hFFFFFFE4,
         32'hFFFFFFE6,
         32'hFFFFFFE2,
         32'hFFFFFFF0,
         32'hFFFFFFFD,
         32'hFFFFFFEA,
         32'hA,
         32'h77,
         32'h25,
         32'h87,
         32'h38,
         32'h64,
         32'h7B,
         32'hEA,
         32'h6D,
         32'hE8,
         32'h56,
         32'hAA,
         32'h89,
         32'h6A,
         32'hD4,
         32'hF5};	// src/main/scala/fpga_lab3/fpga_shell.scala:103:26
      automatic logic [5:0]        _GEN_9;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :84:5
      automatic logic              wrong;	// src/main/scala/fpga_lab3/fpga_shell.scala:143:44
      automatic logic              _GEN_10;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :84:5, :141:13, :144:25
      automatic logic              _GEN_11 = _GEN_1 | _GEN_2 | _GEN_6;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :63:25, :84:5
      automatic logic [5:0]        _GEN_12;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :84:5
      automatic logic              _finish_exe_T_3;	// src/main/scala/fpga_lab3/fpga_shell.scala:148:41
      automatic logic [2:0]        _GEN_13;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :84:5, :141:13, :147:{22,27}, :148:32
      automatic logic              _GEN_14;	// src/main/scala/fpga_lab3/fpga_shell.scala:61:27, :84:5, :141:13, :149:27
      automatic logic [7:0]        _GEN_15;	// src/main/scala/fpga_lab3/fpga_shell.scala:61:27, :84:5, :88:13, :130:23
      automatic logic [7:0][5:0]   _GEN_16;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :84:5, :88:13, :106:21, :117:21
      automatic logic [7:0][5:0]   _GEN_17;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :84:5, :88:13
      automatic logic [7:0][2:0]   _GEN_18;	// src/main/scala/fpga_lab3/fpga_shell.scala:84:5, :88:13, :110:13, :121:13, :126:18, :131:18
      _GEN_9 = _GEN_6 | ~_GEN_5 | is_last ? mem_addr : mem_addr + 6'h1;	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :84:5, :106:31, :135:34, :136:{21,52}
      wrong = _dut_io_dataOut != _GEN_8[rom_addr];	// src/main/scala/fpga_lab3/fpga_shell.scala:57:19, :63:25, :103:26, :143:44
      _GEN_10 = _GEN_5 & REG;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :84:5, :140:25, :141:13, :144:25
      _GEN_12 = _GEN_11 | ~_GEN_10 ? rom_addr : rom_addr + 6'h1;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :84:5, :106:31, :141:13, :144:{25,35}
      _finish_exe_T_3 = rom_addr == 6'h2F;	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :120:26, :148:41
      _GEN_13 = _GEN_5 & REG & (wrong | _finish_exe_T_3) ? 3'h0 : state;	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :84:5, :140:25, :141:13, :143:44, :147:{22,27}, :148:{32,41}
      _GEN_14 = _GEN_10 ? wrong | _finish_exe_T_3 : finish_exe;	// src/main/scala/fpga_lab3/fpga_shell.scala:61:27, :63:25, :84:5, :141:13, :143:44, :144:25, :148:41, :149:{27,32}
      if (_GEN_0 | _GEN_11 | ~_GEN_10) begin	// src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :63:25, :84:5, :141:13, :144:25
      end
      else	// src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :84:5
        result_correct <= ~wrong;	// src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :143:44, :146:34
      _GEN_15 =
        {{_GEN_14},
         {_GEN_14},
         {_GEN_14},
         {~_dut_io_busy},
         {finish_exe},
         {finish_exe},
         {finish_exe},
         {~io_start & finish_exe}};	// src/main/scala/fpga_lab3/fpga_shell.scala:57:19, :61:27, :84:5, :88:13, :90:27, :130:{23,29}, :141:13, :149:27
      finish_exe <= _GEN_15[state];	// src/main/scala/fpga_lab3/fpga_shell.scala:61:27, :77:24, :84:5, :88:13, :130:23
      _GEN_16 =
        {{_GEN_9},
         {_GEN_9},
         {_GEN_9},
         {mem_addr},
         {mem_addr},
         {mem_addr + 6'h1},
         {mem_addr + 6'h1},
         {io_start ? 6'h0 : io_check ? 6'h20 : mem_addr}};	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :84:5, :88:13, :89:25, :94:13, :96:25, :106:{21,31}, :117:{21,31}
      mem_addr <= _GEN_16[state];	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :77:24, :84:5, :88:13, :106:21, :117:21
      _GEN_17 =
        {{_GEN_12},
         {_GEN_12},
         {_GEN_12},
         {rom_addr},
         {rom_addr},
         {rom_addr},
         {rom_addr},
         {io_start | ~io_check ? rom_addr : 6'h20}};	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :84:5, :88:13, :94:13, :96:25
      rom_addr <= _GEN_17[state];	// src/main/scala/fpga_lab3/fpga_shell.scala:63:25, :77:24, :84:5, :88:13
      _GEN_18 =
        {{_GEN_13},
         {_GEN_13},
         {_GEN_13},
         {_dut_io_busy ? state : 3'h0},
         {3'h4},
         {mem_addr == 6'h2F ? 3'h3 : state},
         {mem_addr == 6'h1F ? 3'h2 : state},
         {io_start ? 3'h1 : io_check ? 3'h5 : state}};	// src/main/scala/fpga_lab3/fpga_shell.scala:57:19, :62:25, :77:24, :79:{25,43,59}, :84:5, :88:13, :91:22, :94:13, :98:22, :109:26, :110:{13,20}, :120:26, :121:{13,20}, :126:18, :131:{18,23}, :141:13, :147:{22,27}, :148:32
      state <= _GEN_18[state];	// src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :84:5, :88:13, :110:13, :121:13, :126:18, :131:18
    end
    REG <= _GEN_7;	// src/main/scala/fpga_lab3/fpga_shell.scala:69:18, :84:5, :140:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:851:3
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:851:3
      `FIRRTL_BEFORE_INITIAL	// <stdin>:851:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:851:3
      automatic logic [31:0] _RANDOM[0:0];	// <stdin>:851:3
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:851:3
        `INIT_RANDOM_PROLOG_	// <stdin>:851:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:851:3
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// <stdin>:851:3
        result_correct = _RANDOM[/*Zero width*/ 1'b0][0];	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31
        finish_exe = _RANDOM[/*Zero width*/ 1'b0][1];	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :61:27
        mem_addr = _RANDOM[/*Zero width*/ 1'b0][7:2];	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :62:25
        rom_addr = _RANDOM[/*Zero width*/ 1'b0][13:8];	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :63:25
        state = _RANDOM[/*Zero width*/ 1'b0][16:14];	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :77:24
        REG = _RANDOM[/*Zero width*/ 1'b0][17];	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31, :140:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:851:3
      `FIRRTL_AFTER_INITIAL	// <stdin>:851:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MM_TOP dut (	// src/main/scala/fpga_lab3/fpga_shell.scala:57:19
    .clock      (clock),
    .reset      (reset),
    .io_dataIn  (_GEN_0 | ~_GEN_1 ? 32'h0 : _GEN[mem_addr]),	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25, :66:18, :84:5, :103:26
    .io_addr    (mem_addr),	// src/main/scala/fpga_lab3/fpga_shell.scala:62:25
    .io_writeEn (~_GEN_0 & (_GEN_1 | _GEN_2)),	// src/main/scala/fpga_lab3/fpga_shell.scala:68:19, :84:5, :104:27
    .io_enable  (_GEN_7),	// src/main/scala/fpga_lab3/fpga_shell.scala:69:18, :84:5
    .io_op      ({1'h0, state == 3'h1 | state == 3'h2 | state == 3'h5}),	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:77:24, :79:{14,25,43,52,59}
    .io_start   (~(_GEN_0 | _GEN_4) & _GEN_3),	// src/main/scala/fpga_lab3/fpga_shell.scala:70:18, :84:5
    .io_dataOut (_dut_io_dataOut),
    .io_busy    (_dut_io_busy)
  );
  assign io_finish = finish_exe;	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:61:27
  assign io_correct = result_correct;	// <stdin>:851:3, src/main/scala/fpga_lab3/fpga_shell.scala:60:31
endmodule

module FPGAshell_wrapper(	// <stdin>:1011:3
  input  start_n,	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:11:21
         check_n,	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:12:21
         clk,	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:13:18
         rstn,	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:14:18
  output finish,	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:16:20
         correct	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:17:21
);

  FPGAshell shell (	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:20:54
    .clock      (clk),
    .reset      (~rstn),	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:20:40
    .io_start   (~start_n),	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:22:22
    .io_check   (~check_n),	// src/main/scala/fpga_lab3/fpgashell_wrapper.scala:23:22
    .io_finish  (finish),
    .io_correct (correct)
  );
endmodule

